"""initial_schema

Revision ID: 51fdb1b7e879
Revises:
Create Date: 2026-04-21 22:52:10.049199

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51fdb1b7e879"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trade_name", sa.String(length=150), nullable=False),
        sa.Column("cnpj", sa.String(length=18), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company")),
        sa.UniqueConstraint("cnpj", name=op.f("uq_company_cnpj")),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("corporate_email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["company.id"], name=op.f("fk_user_company_id_company")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(
        op.f("ix_user_corporate_email"),
        "user",
        ["corporate_email"],
        unique=True,
    )
    op.create_index(op.f("ix_user_company_id"), "user", ["company_id"], unique=False)
    op.create_table(
        "psychological_request",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("optional_message", sa.Text(), nullable=True),
        sa.Column(
            "delivery_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_status IN ('pending', 'sent', 'error')",
            name=op.f("ck_psychological_request_delivery_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_psychological_request_user_id_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_psychological_request")),
    )
    op.create_index(
        op.f("ix_psychological_request_user_id"),
        "psychological_request",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "check_in",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("overall_mood", sa.String(length=50), nullable=False),
        sa.Column("answers_json", sa.JSON(), nullable=False),
        sa.Column("stress_level", sa.Integer(), nullable=False),
        sa.Column("ai_insights", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stress_level >= 0 AND stress_level <= 100",
            name=op.f("ck_check_in_stress_level_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_check_in_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_in")),
    )
    op.create_index(op.f("ix_check_in_user_id"), "check_in", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_check_in_user_id"), table_name="check_in")
    op.drop_table("check_in")
    op.drop_index(
        op.f("ix_psychological_request_user_id"), table_name="psychological_request"
    )
    op.drop_table("psychological_request")
    op.drop_index(op.f("ix_user_company_id"), table_name="user")
    op.drop_index(op.f("ix_user_corporate_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("company")
    # ### end Alembic commands ###
